Development
fmanimashaun/My-Portfolio pull request #1
Opened 2022-09-21 21:28 UTC by fmanimashaun

# The initial project setup

> Basically, this is just the initial project folder setup and other related files and branch

2022-09-23 23:28 UTC, nedjwab requested changes
# Changes Required ♻️
### Hi @fmanimashaun 

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :
- Good implementation of some of the project requirements  ✔
- GitHub flow was correctly used ✔.
- Good design 🔥🔥🔥

## (Changes Required) Aspects to improve: ♻️
You did great implementing  the project requirements, but you still have some issues: 
 
## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-23 23:28 UTC, nedjwab commented on index.html
> +        <nav class="mobile-menu-modal close-menu">
[ ] kindly use a `header` tag for the main site navigation.[ check this article ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header)👀

2022-09-23 23:28 UTC, nedjwab commented on index.html
> +                <article class="hero-social">
[ ] kindly use a `ul` tag for The list of icons. and `li` per icon, each icon has a link a` tag `.The links should be your social media links.🤓

2022-09-23 23:28 UTC, nedjwab commented on README.md
[ ] kindly add a usage section to the README file, to explain how we set up and run the project locally.👀

2022-09-24 00:06 UTC, fmanimashaun commented on index.html
> +        <nav class="mobile-menu-modal close-menu">
# Main  site navigation issue

- The main site navigation is within the header already
- What you are referencing is the mobile menu modal HTML structured which has been referenced to the container div
- I have added additional comments in the HTML file for clarity

2022-09-24 00:19 UTC, fmanimashaun commented on README.md
# Resolved the social media HTML structure
- Thanks for the feedback, it has been implemented as recommended.

2022-09-24 00:20 UTC, fmanimashaun commented on index.html
> +                <article class="hero-social">
# Resolved the social media HTML structure
- Thanks for the feedback, it has been implemented as recommended.

2022-09-24 00:23 UTC, fmanimashaun commented on README.md
# Usage section
- Well, in my view, I feel it is not needed as the project is a static website (personal portfolio). 
- But if you insist, I might reconsider my stance on it (Cheers).

2022-09-24 00:35 UTC, mgmediaweb commented on index.html
> +        <nav class="mobile-menu-modal close-menu">
Kindly, I recommend you follow the suggestions of the previous reviewer, I enclose a basic structure of what a header should look like

![carbon (6)](https://user-images.githubusercontent.com/41912912/192072379-73e5707b-4912-413f-9840-35c31722a3a0.png)

2022-09-24 00:35 UTC, mgmediaweb commented on index.html
> +                <article class="hero-social">
Good job following the advice of the previous reviewer

2022-09-24 00:38 UTC, mgmediaweb requested changes
Hi @fmanimashaun , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost1](https://user-images.githubusercontent.com/41912912/192072544-a42866d6-6309-477a-a096-96d61dffaef7.gif)

 ## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 00:48 UTC, fmanimashaun commented on index.html
> +        <nav class="mobile-menu-modal close-menu">
# Header structure

- As stated earlier, the header is well structured with the main site navigation within the header element (see index.html for reference
- I have adjusted the logo section as recommended and referenced it to the hero section for return navigation back to the top (*will be implemented in future project with javascript*

2022-09-24 01:10 UTC, MaganaAsiati approved these changes
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @fmanimashaun, I'm @MaganaAsiati, your reviewer for this PR  :wave: 
Great work on making the changes requested by a previous reviewer 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


<img src="https://media2.giphy.com/media/ByeYxURXxPyptxD2ta/giphy-downsized-medium.gif"/>


## Highlights
- Descriptive pull request :heavy_check_mark:👨🏻‍💻
- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.
- [ ] [OPTIONAL] I suggest you remove the comment message inside your code it will make your code look clear and more readable  :grinning:  :grinning:  :grinning: 



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
Cheers and Happy coding! 🤓 👏👏👏

2022-09-24 01:15 UTC, merged